baseControlType:
  baseVelocityControl: true
  basePositionControl: false
  baseJointVelocityControl: false
  baseJointCurrentControl: false
  baseJointToqueControl: false

armControlType:
  armJointPositionControl: true
  armJointVelocityControl: false
  armJointToqueControl: false
